name: Continuous Integration

on: [ push ]

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        php-version:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
        dependencies:
          - lowest
          - highest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install lowest dependencies
        if: ${{ matrix.dependencies == 'lowest' }}
        run: composer update --prefer-lowest --no-interaction --no-progress

      - name: Install highest dependencies
        if: ${{ matrix.dependencies == 'highest' }}
        run: composer update --no-interaction --no-progress

      - name: Run test suite
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml
